CREATE TABLE TUTORIAL (
    SLUGS TEXT  PRIMARY KEY,
    SYSTEM_PATH TEXT,
    CATEGORY TEXT,
    FILENAME TEXT,
    TITLE TEXT,
    DESCRIPTION TEXT,
    AUTHOR TEXT,
    PUBLISHED TEXT,
    UPDATED TEXT,
    PREV TEXT
);